# -*- coding: utf-8 -*-
"""Xray_DiseasePredictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J2h2Xn4ev8E2PoGrYU10KpRCSFuaa7C4
"""

import torch
from diffusers import StableDiffusionPipeline
import os
import shutil

# ==========================================
# 1. SETUP MODEL
# ==========================================
model_id = "runwayml/stable-diffusion-v1-5"
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
pipe = pipe.to("cuda")

# ==========================================
# 2. DEFINE CATEGORIES AND PROMPTS
# ==========================================
# We map your specific categories to detailed prompts to get the best X-ray look.
# Key = The Folder Name (Label)
# Value = The Prompt for the AI
data_categories = {
    "Normal_Anatomy": "A high quality medical chest X-ray of healthy lungs, PA view, clear diaphragm, sharp bony structures, monochrome, radiography",

    "Infectious_Patterns": "A chest X-ray showing bacterial pneumonia with lobar consolidation, medical imaging, black and white radiograph",

    "Lung_Opacities": "A chest X-ray showing ground-glass opacities in the lungs, diffuse haziness, medical diagnosis image",

    "Pleural_Conditions": "A chest X-ray showing pleural effusion, fluid accumulation at the lung base, blunted costophrenic angle",

    "Structural_Lesions": "A chest X-ray showing a pulmonary nodule in the right upper lobe, medical screening, high contrast",

    "Cardiac_Findings": "A chest X-ray showing cardiomegaly, enlarged heart silhouette, vascular congestion, medical imaging",

    "Medical_Devices": "A chest X-ray showing a pacemaker implanted in the chest wall with leads extending to the heart, medical device artifact",

    "Imaging_Artifacts": "A low quality chest X-ray with motion blur and noise, poor exposure, medical imaging artifact",

    "View_Positioning": "A chest X-ray, AP view, patient in supine position, portable X-ray machine quality",

    "Domain_Shift": "A chest X-ray scanned from a film, different hospital protocol, slightly different contrast resolution"
}

# ==========================================
# 3. GENERATE AND SAVE WITH LABELS
# ==========================================
base_folder = "synthetic_xray_dataset"

# Clean up previous run if it exists
if os.path.exists(base_folder):
    shutil.rmtree(base_folder)
os.makedirs(base_folder)

print(f"Generating data for {len(data_categories)} categories...\n")

for label, prompt_text in data_categories.items():
    # Create a sub-folder for this specific label (Class)
    # This fulfills the requirement to "give label and image"
    class_folder = os.path.join(base_folder, label)
    os.makedirs(class_folder, exist_ok=True)

    print(f"Processing Category: {label}...")

    # We generate 2 images per category just to show variation
    for i in range(2):
        # Using a generator with a different seed for every image ensures they look different
        generator = torch.Generator("cuda").manual_seed(2024 + i + len(label))

        # Adding "photorealistic, medical x-ray" to every prompt to enforce style
        full_prompt = f"{prompt_text}, photorealistic, medical x-ray style, high definition"

        image = pipe(full_prompt, generator=generator).images[0]

        # Save image: Label_Index.png
        filename = f"{label}_{i+1}.png"
        image.save(os.path.join(class_folder, filename))

print(f"\nSuccess! Dataset created at: {base_folder}")

# ==========================================
# 4. DISPLAY SAMPLES
# ==========================================
import matplotlib.pyplot as plt

# Pick the first image from 5 categories to display
display_labels = list(data_categories.keys())[:5]

plt.figure(figsize=(20, 5))
for i, label in enumerate(display_labels):
    img_path = os.path.join(base_folder, label, f"{label}_1.png")
    if os.path.exists(img_path):
        img = plt.imread(img_path)
        plt.subplot(1, 5, i+1)
        plt.imshow(img, cmap='gray') # Display in grayscale
        plt.title(label)
        plt.axis('off')

plt.show()