# -*- coding: utf-8 -*-
"""GenAI Week10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pnSbSTTwomkCGY7i3Jr9p4pSvwVe9CJN
"""

import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Embedding, LSTM, Dense
from tensorflow.keras.callbacks import Callback
import matplotlib.pyplot as plt
from tensorflow.keras import layers

text_data = [
 "artificial intelligence systems learn patterns from data.",
 "sequence models process information step by step.",
 "recurrent neural networks are useful for sequence prediction.",
 "lstm networks handle long term dependencies.",
 "deep learning models improve sequence learning.",
 "generative models create new samples from learned patterns.",
 "language models predict the next word in a sentence.",
 "sequence generation is used in chatbots and assistants.",
 "machine learning helps computers learn automatically.",
 "training data improves model accuracy.",
 "neural networks simulate human brain structures.",
 "optimization algorithms improve learning efficiency.",
 "technology is transforming modern education.",
 "online learning platforms use artificial intelligence.",
 "students benefit from intelligent tutoring systems.",
 "automation improves productivity and decision making."
]

tokenizer = Tokenizer()
tokenizer.fit_on_texts(text_data)

total_words = len(tokenizer.word_index) + 1
index_to_word = tokenizer.index_word

input_sequences = []

for line in text_data:
    token_list = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(token_list)):
        n_gram_seq = token_list[:i+1]
        input_sequences.append(n_gram_seq)

max_sequence_len = max(len(seq) for seq in input_sequences)

input_sequences = pad_sequences(input_sequences, maxlen=max_sequence_len, padding='pre')

X, y = input_sequences[:, :-1], input_sequences[:, -1]
y = tf.keras.utils.to_categorical(y, num_classes=total_words)

"""LSTM"""

model_lstm = Sequential([
    Input(shape=(max_sequence_len-1,)),
    Embedding(total_words, 64),
    LSTM(150),
    Dense(total_words, activation='softmax')
])

model_lstm.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model_lstm.summary()

class PrintEveryNEpochs(Callback):
    def __init__(self, interval=20):
        self.interval = interval

    def on_epoch_end(self, epoch, logs=None):
        if (epoch + 1) % self.interval == 0:
            print(f"Epoch {epoch+1}: Loss={logs['loss']:.4f}, Acc={logs['accuracy']:.4f}")

history_lstm = model_lstm.fit(
    X, y,
    epochs=100,
    verbose=0,
    callbacks=[PrintEveryNEpochs(20)]
)

def generate_sequence(seed_text, next_words, model):
    for _ in range(next_words):
        token_list = tokenizer.texts_to_sequences([seed_text])[0]
        token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')

        predicted = model.predict(token_list, verbose=0)
        predicted_word = index_to_word[np.argmax(predicted)]

        seed_text += " " + predicted_word

    return seed_text

print("\n--- LSTM Output ---")
seed = "artificial intelligence"
print(generate_sequence(seed, 5, model_lstm))

"""Transformer

"""

class TokenAndPositionEmbedding(layers.Layer):
    def __init__(self, maxlen, vocab_size, embed_dim):
        super().__init__()
        self.token_emb = layers.Embedding(vocab_size, embed_dim)
        self.pos_emb = layers.Embedding(maxlen, embed_dim)

    def call(self, x):
        positions = tf.range(start=0, limit=tf.shape(x)[-1], delta=1)
        positions = self.pos_emb(positions)
        x = self.token_emb(x)
        return x + positions


class TransformerBlock(layers.Layer):
    def __init__(self, embed_dim, num_heads, ff_dim):
        super().__init__()
        self.att = layers.MultiHeadAttention(num_heads=num_heads, key_dim=embed_dim)
        self.ffn = tf.keras.Sequential([
            layers.Dense(ff_dim, activation="relu"),
            layers.Dense(embed_dim)
        ])
        self.norm1 = layers.LayerNormalization()
        self.norm2 = layers.LayerNormalization()

    def call(self, x):
        attn = self.att(x, x)
        x = self.norm1(x + attn)
        ffn = self.ffn(x)
        return self.norm2(x + ffn)

embed_dim = 64
num_heads = 2
ff_dim = 128

inputs = layers.Input(shape=(max_sequence_len-1,))
x = TokenAndPositionEmbedding(max_sequence_len-1, total_words, embed_dim)(inputs)
x = TransformerBlock(embed_dim, num_heads, ff_dim)(x)
x = layers.GlobalAveragePooling1D()(x)
x = layers.Dense(64, activation="relu")(x)
outputs = layers.Dense(total_words, activation="softmax")(x)

model_transformer = tf.keras.Model(inputs, outputs)

model_transformer.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

model_transformer.summary()

history_transformer = model_transformer.fit(
    X, y,
    epochs=100,
    verbose=0,
    callbacks=[PrintEveryNEpochs(20)]
)

print("\n--- Transformer Output ---")
seed = "generative models"
print(generate_sequence(seed, 5, model_transformer))

plt.plot(history_lstm.history['loss'], label='LSTM')
plt.plot(history_transformer.history['loss'], label='Transformer')
plt.legend()
plt.title("Loss Comparison")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.show()